"""initial_migration

Revision ID: 4703e6ea0868
Revises:
Create Date: 2023-10-23 19:19:10.372220

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4703e6ea0868"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parlays",
        sa.Column("token", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_token", sa.String(), nullable=False),
        sa.Column("event_token", sa.String(), nullable=False),
        sa.Column("amount", sa.String(), nullable=False),
        sa.Column("coefficient", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "WENT_IN", "LOST", name="parlaystatus"), nullable=False),
        sa.Column("status_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index("events_user_token_created_at_idx", "parlays", ["user_token", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("events_user_token_created_at_idx", table_name="parlays")
    op.drop_table("parlays")
    # ### end Alembic commands ###
