---
version: '3.8'

services:
  bet-maker-db-test:
    image: postgres:14.5
    container_name: btw-postgres-bet-maker-test
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: betwise-test
      POSTGRES_PASSWORD: betwise-test
      POSTGRES_DB: betwise-test
    tty: true
    networks:
      - btw-dev-network
  bet-maker-db-local:
    image: postgres:14.5
    container_name: btw-postgres-bet-maker
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: betwise
      POSTGRES_PASSWORD: betwise
      POSTGRES_DB: betwise
    volumes:
      - pgdata_bet_maker:/var/lib/postgresql/bet-maker-data
    tty: true
    networks:
      - btw-dev-network
  bet-maker:
    container_name: btw-bet-maker
    platform: linux/x86_64
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    restart: always
    volumes:
      - ../src:/src
      - ../opt:/opt
    ports:
      - "8062:8000"
    environment:
      - API_ENVIRONMENT=local
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - btw-dev-network
    tty: true
    depends_on:
      - bet-maker-db-test
      - bet-maker-db-local
  bet-maker-consumer:
    container_name: btw-bet-maker-consumer
    platform: linux/x86_64
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    restart: always
    command: [ "python3", "message_consumers/event_statuses/consumer.py" ]
    volumes:
      - ../src:/src
    environment:
      - API_ENVIRONMENT=local
    networks:
      - btw-dev-network
    tty: true
    depends_on:
      - bet-maker-db-test
      - bet-maker-db-local
  redis:
    container_name: btw-redis
    image: redis:7.0.11
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --requirepass betwise
    networks:
      - btw-dev-network
  sqs:
    image: softwaremill/elasticmq-native
    container_name: btw-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./sqs/sqs_config.conf:/opt/elasticmq.conf
    networks:
      - btw-dev-network
networks:
  btw-dev-network:
    external: true
volumes:
  pgdata_bet_maker:
